name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RELEASE_DIR=/var/www/frontend/releases/$TIMESTAMP

          echo "🚀 Creating release folder $RELEASE_DIR"
          ssh -i $PRIVATE_KEY $USER@$HOST "mkdir -p $RELEASE_DIR"

          echo "📂 Uploading build to $RELEASE_DIR"
          scp -i $PRIVATE_KEY -r build/* $USER@$HOST:$RELEASE_DIR

          echo "🔗 Updating symlink"
          ssh -i $PRIVATE_KEY $USER@$HOST "ln -sfn $RELEASE_DIR /var/www/frontend/current"

          echo "🗑 Cleaning up old releases (keep last 5)"
          ssh -i $PRIVATE_KEY $USER@$HOST "
            cd /var/www/frontend/releases &&
            ls -1t | tail -n +6 | xargs -I {} rm -rf {} || true
          "

          echo "✅ Frontend deployed successfully!"
